apiVersion: v1
kind: Service
metadata:
  name: open-liberty-rest-intro-sgx
  labels:
    app: open-liberty-rest-intro-sgx
spec:
  type: LoadBalancer
  selector:
    app: open-liberty-rest-intro-sgx
  ports:
    - name: http
      port: 80
      targetPort: 9080
---
kind: Pod
apiVersion: v1
metadata:
  name: open-liberty-rest-intro-sgx
  labels:
    app: open-liberty-rest-intro-sgx
spec:
  containers:
  - name: open-liberty-rest-intro-sgx
    image: <your-registry>/open-liberty-rest-intro-sgx:20190219-423b695
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 9080
      name: http
      protocol: TCP
  volumes:
  - name: isgx
    hostPath:
      path: /dev/isgx
  - name: gsgx
    hostPath:
      path: /dev/gsgx
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
