apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-sgx
  labels:
    app: spring-mysql-sgx
spec:
  type: LoadBalancer
  selector:
    app: spring-mysql-sgx
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: spring-mysql-sgx
  labels:
    app: spring-mysql-sgx
spec:
  containers:
  - name: spring-mysql-db-sgx
    image: <your-registry>/spring-mysql-db-sgx:20190206-220832d
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
  - name: spring-mysql-app-sgx
    image: <your-registry>/spring-mysql-app-sgx:20190206-220832d
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 8080
      name: spring-mysql
      protocol: TCP
  volumes:
  - name: isgx
    hostPath:
      path: /dev/isgx
  - name: gsgx
    hostPath:
      path: /dev/gsgx
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
