apiVersion: v1
kind: Service
metadata:
  name: ewallet
  labels:
    app: ewallet
spec:
  type: LoadBalancer
  selector:
    app: ewallet
  ports:
    - name: http
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: ewallet
  labels:
    app: ewallet
spec:
  containers:
  - name: ewallet-db
    image: fortanix/ewallet-db:20181031-4732528
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
  - name: ewallet
    image: fortanix/ewallet:20181031-4732528
    ports:
    - containerPort: 5000
      name: ewallet
      protocol: TCP
    env:
    - name: MYSQL_HOST
      value: 127.0.0.1
    - name: MYSQL_ROOT_PASSWORD
      value: password
  - name: ewallet-nginx
    image: fortanix/ewallet-nginx:20181031-4732528
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
