apiVersion: v1
kind: Service
metadata:
  name: ewallet-sgx
  labels:
    app: ewallet-sgx
spec:
  type: LoadBalancer
  selector:
    app: ewallet-sgx
  ports:
    - name: http
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: ewallet-sgx
  labels:
    app: ewallet-sgx
spec:
  containers:
  - name: ewallet-db-sgx
    image: <your-registry>/ewallet-db-sgx:20181031-4732528
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
  - name: ewallet-sgx
    image: <your-registry>/ewallet-sgx:20181031-4732528
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 5000
      name: ewallet
      protocol: TCP
    env:
    - name: MYSQL_HOST
      value: 127.0.0.1
    - name: MYSQL_ROOT_PASSWORD
      value: password
  - name: ewallet-nginx-sgx
    image: <your-registry>/ewallet-nginx-sgx:20181031-4732528
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
  volumes:
  - name: isgx
    hostPath:
      path: /dev/isgx
  - name: gsgx
    hostPath:
      path: /dev/gsgx
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
