apiVersion: v1
kind: Service
metadata:
  name: ewallet-sgx
  labels:
    app: ewallet-sgx
spec:
  type: LoadBalancer
  selector:
    app: ewallet-sgx
  ports:
    - name: https
      port: 443
      targetPort: 443
---
kind: Pod
apiVersion: v1
metadata:
  name: ewallet-sgx
  labels:
    app: ewallet-sgx
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "ewallet-db-sgx"
    - "ewallet-app-sgx"
  containers:
  - name: ewallet-db-sgx
    image: registry.ng.bluemix.net/datashield-dev/ewallet-db-sgx:20181214-803cab7
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    env:
    - name: EWALLET_USER
      value: ewallet-app-sgx
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NODE_AGENT_BASE_URL
      value: http://$(NODE_IP):9092/v1
  - name: ewallet-app-sgx
    image: registry.ng.bluemix.net/datashield-dev/ewallet-sgx:20181214-803cab7
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 5000
      name: ewallet
      protocol: TCP
    env:
    - name: MYSQL_HOST
      value: ewallet-db-sgx
    - name: MYSQL_USER
      value: ewallet
    - name: MYSQL_PASSWORD
      value: password
    - name: SERVER_CERT_FILE
      value: /etc/ewallet/cert.pem
    - name: SERVER_KEY_FILE
      value: /etc/ewallet/key.pem
    - name: CA_CERT_FILE
      value: /etc/ssl/certs/ca-cert.pem
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NODE_AGENT_BASE_URL
      value: http://$(NODE_IP):9092/v1
  - name: ewallet-nginx-sgx
    image: registry.ng.bluemix.net/datashield-dev/ewallet-nginx-sgx:20181214-803cab7
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    ports:
    - containerPort: 443
      name: https
      protocol: TCP
    env:
    - name: PROXY_PASS_URL
      value: https://ewallet-app-sgx:9090/
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NODE_AGENT_BASE_URL
      value: http://$(NODE_IP):9092/v1
  volumes:
  - name: isgx
    hostPath:
      path: /dev/isgx
  - name: gsgx
    hostPath:
      path: /dev/gsgx
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
